server.port=8095

spring.datasource.url=jdbc:sqlite:${user.dir}/data/elderly_care.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=

spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=Asia/Shanghai
spring.jackson.serialization.write-dates-as-timestamps=false

spring.sql.init.mode=never
